export const DEMO_REWARDS_PROGRAMS = [
  { id: 'amex', name: 'Amex', program: 'Membership Rewards', mark: 'AM', balance: 342800, color: '#1769aa', tint: '#eaf5ff', featured: true },
  { id: 'chase', name: 'Chase', program: 'Ultimate Rewards', mark: 'CH', balance: 186400, color: '#146b5b', tint: '#e8f6f1', featured: true },
  { id: 'capitalone', name: 'Capital One', program: 'Miles', mark: 'C1', balance: 91800, color: '#a01f46', tint: '#fff0f4', featured: true },
  { id: 'citi', name: 'Citi', program: 'ThankYou Rewards', mark: 'CI', balance: 128600, color: '#056dae', tint: '#eaf5fb', featured: true },
  { id: 'bilt', name: 'Bilt', program: 'Rewards', mark: 'BI', balance: 74600, color: '#2d3132', tint: '#f0f1f1', featured: true },
  { id: 'american', name: 'American', program: 'AAdvantage', mark: 'AA', balance: 84400, color: '#c3273c', tint: '#fff0f2', featured: true },
  { id: 'united', name: 'United', program: 'MileagePlus', mark: 'UA', balance: 62100, color: '#174ea6', tint: '#edf3ff', featured: true },
  { id: 'delta', name: 'Delta', program: 'SkyMiles', mark: 'DL', balance: 53750, color: '#9b1834', tint: '#fff0f4', featured: true },
  { id: 'southwest', name: 'Southwest', program: 'Rapid Rewards', mark: 'WN', balance: 47600, color: '#304cb2', tint: '#eef1ff', featured: true },
  { id: 'aeroplan', name: 'Aeroplan', program: 'Air Canada', mark: 'AC', balance: 41250, color: '#d8292f', tint: '#fff0f0', featured: true },
  { id: 'flyingblue', name: 'Flying Blue', program: 'Air France · KLM', mark: 'FB', balance: 28750, color: '#293893', tint: '#eef0ff', featured: true },
  { id: 'alaska', name: 'Alaska', program: 'Atmos Rewards', mark: 'AS', balance: 36400, color: '#005f6a', tint: '#e9f6f7', featured: true },
  { id: 'jetblue', name: 'JetBlue', program: 'TrueBlue', mark: 'B6', balance: 23100, color: '#003876', tint: '#edf3fa', featured: true },
  { id: 'britishairways', name: 'British Airways', program: 'The British Airways Club', mark: 'BA', balance: 52900, color: '#1b3f8b', tint: '#eef2fb' },
  { id: 'virginatlantic', name: 'Virgin Atlantic', program: 'Flying Club', mark: 'VS', balance: 44750, color: '#c4143c', tint: '#fff0f4' },
  { id: 'singapore', name: 'Singapore Airlines', program: 'KrisFlyer', mark: 'SQ', balance: 31800, color: '#d19b2a', tint: '#fff8e8' },
  { id: 'emirates', name: 'Emirates', program: 'Skywards', mark: 'EK', balance: 26400, color: '#c52732', tint: '#fff0f1' },
  { id: 'qatar', name: 'Qatar Airways', program: 'Privilege Club', mark: 'QR', balance: 35600, color: '#6d1740', tint: '#f8edf2' },
  { id: 'cathay', name: 'Cathay Pacific', program: 'Asia Miles', mark: 'CX', balance: 24900, color: '#0c776c', tint: '#ebf7f5' },
  { id: 'turkish', name: 'Turkish Airlines', program: 'Miles&Smiles', mark: 'TK', balance: 21400, color: '#c5162e', tint: '#fff0f2' },
  { id: 'wellsfargo', name: 'Wells Fargo', program: 'Rewards', mark: 'WF', balance: 48600, color: '#b31b34', tint: '#fff0f2' },
  { id: 'avianca', name: 'Avianca', program: 'LifeMiles', mark: 'AV', balance: 33700, color: '#d71920', tint: '#fff0f0' },
  { id: 'qantas', name: 'Qantas', program: 'Frequent Flyer', mark: 'QF', balance: 29500, color: '#d51b2b', tint: '#fff0f1' },
  { id: 'etihad', name: 'Etihad Airways', program: 'Etihad Guest', mark: 'EY', balance: 27300, color: '#8a6c3d', tint: '#f8f3ea' },
  { id: 'korean', name: 'Korean Air', program: 'SKYPASS', mark: 'KE', balance: 19200, color: '#2369b3', tint: '#edf5fc' },
  { id: 'bankofamerica', name: 'Bank of America', program: 'Preferred Rewards', mark: 'BO', balance: 68400, color: '#c41230', tint: '#fff0f3' },
  { id: 'usbank', name: 'U.S. Bank', program: 'Altitude Rewards', mark: 'US', balance: 55700, color: '#154a86', tint: '#edf4fb' },
  { id: 'barclays', name: 'Barclays', program: 'Barclays Rewards', mark: 'BC', balance: 43100, color: '#00a2df', tint: '#eaf8fd' },
  { id: 'brex', name: 'Brex', program: 'Brex Rewards', mark: 'BX', balance: 39200, color: '#ff5a1f', tint: '#fff2ec' },
  { id: 'rbc', name: 'RBC', program: 'Avion Rewards', mark: 'RB', balance: 67300, color: '#006ac3', tint: '#edf6ff' },
  { id: 'td', name: 'TD', program: 'TD Rewards', mark: 'TD', balance: 51800, color: '#128842', tint: '#ebf8ef' },
  { id: 'cibc', name: 'CIBC', program: 'Aventura', mark: 'CB', balance: 44700, color: '#8b1d41', tint: '#faeef3' },
  { id: 'bmo', name: 'BMO', program: 'BMO Rewards', mark: 'BM', balance: 48600, color: '#0075be', tint: '#edf7fc' },
  { id: 'sceneplus', name: 'Scene+', program: 'Scene+ Rewards', mark: 'SC', balance: 32800, color: '#7c3aed', tint: '#f3efff' },
  { id: 'westjet', name: 'WestJet', program: 'WestJet Rewards', mark: 'WS', balance: 27900, color: '#007b83', tint: '#eaf7f7' },
  { id: 'lufthansa', name: 'Lufthansa Group', program: 'Miles & More', mark: 'LH', balance: 38600, color: '#05164d', tint: '#eef1f8' },
  { id: 'sas', name: 'SAS', program: 'EuroBonus', mark: 'SK', balance: 31100, color: '#12347a', tint: '#eef3fb' },
  { id: 'finnair', name: 'Finnair', program: 'Finnair Plus', mark: 'AY', balance: 25800, color: '#0b1560', tint: '#eff1fb' },
  { id: 'iberia', name: 'Iberia', program: 'Iberia Club', mark: 'IB', balance: 34700, color: '#d7192d', tint: '#fff0f2' },
  { id: 'aerlingus', name: 'Aer Lingus', program: 'AerClub', mark: 'EI', balance: 22600, color: '#007a53', tint: '#eaf7f2' },
  { id: 'tap', name: 'TAP Air Portugal', program: 'Miles&Go', mark: 'TP', balance: 28300, color: '#087c55', tint: '#edf8f3' },
  { id: 'aegean', name: 'Aegean Airlines', program: 'Miles+Bonus', mark: 'A3', balance: 20400, color: '#164194', tint: '#edf3fc' },
  { id: 'ita', name: 'ITA Airways', program: 'Volare', mark: 'AZ', balance: 21900, color: '#006b5c', tint: '#eaf7f4' },
  { id: 'ana', name: 'ANA', program: 'Mileage Club', mark: 'NH', balance: 37100, color: '#17479e', tint: '#eef3fb' },
  { id: 'jal', name: 'Japan Airlines', program: 'Mileage Bank', mark: 'JL', balance: 33400, color: '#c8102e', tint: '#fff0f3' },
  { id: 'eva', name: 'EVA Air', program: 'Infinity MileageLands', mark: 'BR', balance: 26100, color: '#007f67', tint: '#eaf7f3' },
  { id: 'chinaairlines', name: 'China Airlines', program: 'Dynasty Flyer', mark: 'CI', balance: 23800, color: '#8a2d78', tint: '#f8eef6' },
  { id: 'thai', name: 'Thai Airways', program: 'Royal Orchid Plus', mark: 'TG', balance: 24700, color: '#5b2c83', tint: '#f4eff9' },
  { id: 'garuda', name: 'Garuda Indonesia', program: 'GarudaMiles', mark: 'GA', balance: 19400, color: '#007c91', tint: '#eaf7f9' },
  { id: 'malaysia', name: 'Malaysia Airlines', program: 'Enrich', mark: 'MH', balance: 21600, color: '#0b3c78', tint: '#eef4fb' },
  { id: 'vietnam', name: 'Vietnam Airlines', program: 'Lotusmiles', mark: 'VN', balance: 18500, color: '#007f95', tint: '#eaf8fa' },
  { id: 'philippine', name: 'Philippine Airlines', program: 'Mabuhay Miles', mark: 'PR', balance: 17300, color: '#003876', tint: '#edf3fa' },
  { id: 'airindia', name: 'Air India', program: 'Maharaja Club', mark: 'AI', balance: 29200, color: '#d71920', tint: '#fff0f0' },
  { id: 'indigo', name: 'IndiGo', program: 'BluChip', mark: '6E', balance: 15600, color: '#242f83', tint: '#eff1fb' },
  { id: 'virginaustralia', name: 'Virgin Australia', program: 'Velocity', mark: 'VA', balance: 30500, color: '#d5003c', tint: '#fff0f4' },
  { id: 'airnewzealand', name: 'Air New Zealand', program: 'Airpoints', mark: 'NZ', balance: 22400, color: '#111111', tint: '#f1f2f1' },
  { id: 'latam', name: 'LATAM Airlines', program: 'LATAM Pass', mark: 'LA', balance: 31800, color: '#5c2d91', tint: '#f4effa' },
  { id: 'copa', name: 'Copa Airlines', program: 'ConnectMiles', mark: 'CM', balance: 26900, color: '#17365d', tint: '#eff3f8' },
  { id: 'azul', name: 'Azul', program: 'Azul Fidelidade', mark: 'AD', balance: 24700, color: '#005daa', tint: '#edf5fc' },
  { id: 'gol', name: 'GOL', program: 'Smiles', mark: 'G3', balance: 28600, color: '#f58220', tint: '#fff5eb' },
  { id: 'aeromexico', name: 'Aeromexico', program: 'Aeromexico Rewards', mark: 'AM', balance: 25400, color: '#0b2343', tint: '#eef2f7' },
  { id: 'saudia', name: 'Saudia', program: 'AlFursan', mark: 'SV', balance: 23200, color: '#006c55', tint: '#eaf7f2' },
  { id: 'oman', name: 'Oman Air', program: 'Sindbad', mark: 'WY', balance: 19800, color: '#b89c5b', tint: '#faf6ec' },
  { id: 'elal', name: 'EL AL', program: 'Matmid', mark: 'LY', balance: 21100, color: '#0054a6', tint: '#edf5fc' },
  { id: 'ethiopian', name: 'Ethiopian Airlines', program: 'ShebaMiles', mark: 'ET', balance: 26400, color: '#078930', tint: '#edf8f0' },
  { id: 'kenya', name: 'Kenya Airways', program: 'Asante Rewards', mark: 'KQ', balance: 18100, color: '#b5121b', tint: '#fff0f1' },
  { id: 'southafrican', name: 'South African Airways', program: 'Voyager', mark: 'SA', balance: 20300, color: '#007749', tint: '#eaf7f1' },
  { id: 'egyptair', name: 'EgyptAir', program: 'EgyptAir Plus', mark: 'MS', balance: 18900, color: '#0f4c81', tint: '#eef5fa' },
  { id: 'royalairmaroc', name: 'Royal Air Maroc', program: 'Safar Flyer', mark: 'AT', balance: 17500, color: '#c62026', tint: '#fff0f1' },
  { id: 'marriott', name: 'Marriott', program: 'Marriott Bonvoy', mark: 'MB', balance: 96400, color: '#8b1f41', tint: '#faeef3' },
  { id: 'hilton', name: 'Hilton', program: 'Hilton Honors', mark: 'HH', balance: 118500, color: '#003b70', tint: '#edf3f9' },
  { id: 'hyatt', name: 'Hyatt', program: 'World of Hyatt', mark: 'HY', balance: 42600, color: '#4b7f8f', tint: '#eef6f8' },
  { id: 'ihg', name: 'IHG', program: 'IHG One Rewards', mark: 'IH', balance: 88700, color: '#6b1d5c', tint: '#f7eef5' },
  { id: 'wyndham', name: 'Wyndham', program: 'Wyndham Rewards', mark: 'WR', balance: 53400, color: '#005eb8', tint: '#edf5fd' },
  { id: 'choice', name: 'Choice Hotels', program: 'Choice Privileges', mark: 'CP', balance: 39200, color: '#004b8d', tint: '#eef4fa' },
  { id: 'accor', name: 'Accor', program: 'ALL', mark: 'AL', balance: 28400, color: '#1e1852', tint: '#f1f0f8' },
  { id: 'radisson', name: 'Radisson', program: 'Radisson Rewards', mark: 'RR', balance: 46700, color: '#5b2b82', tint: '#f4eff9' },
]
